apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lvwwfn6b1-nodejs 
  janus-idp.io/tekton: lvwwfn6b1-nodejs
  backstage.io/kubernetes-id: lvwwfn6b1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lvwwfn6b1-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml